// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASZsm053y_D4xZmzoN5-ML9fpUj_ghz3I',
    appId: '1:875443351989:web:5e989b6f5e92b5e21769fc',
    messagingSenderId: '875443351989',
    projectId: 'techi4u-e-commerce',
    authDomain: 'techi4u-e-commerce.firebaseapp.com',
    storageBucket: 'techi4u-e-commerce.appspot.com',
    measurementId: 'G-MCYC1WGX79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr9kPxTcefqirjHIBGGB0FKUfLAlQmbkk',
    appId: '1:875443351989:android:0ac8ee87ddd9154f1769fc',
    messagingSenderId: '875443351989',
    projectId: 'techi4u-e-commerce',
    storageBucket: 'techi4u-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMOYgz8qE88dLJFOShDyB__STzV-VYMd8',
    appId: '1:875443351989:ios:427b86f2c90824801769fc',
    messagingSenderId: '875443351989',
    projectId: 'techi4u-e-commerce',
    storageBucket: 'techi4u-e-commerce.appspot.com',
    iosBundleId: 'com.example.techi4uECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMOYgz8qE88dLJFOShDyB__STzV-VYMd8',
    appId: '1:875443351989:ios:792d322426e754c01769fc',
    messagingSenderId: '875443351989',
    projectId: 'techi4u-e-commerce',
    storageBucket: 'techi4u-e-commerce.appspot.com',
    iosBundleId: 'com.example.techi4uECommerce.RunnerTests',
  );
}
